# Generated by Django 5.2.1 on 2025-06-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AsistentesEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asi_eve_fecha_hora', models.DateTimeField()),
                ('asi_eve_soporte', models.CharField(blank=True, max_length=255, null=True)),
                ('asi_eve_estado', models.CharField(max_length=45)),
                ('asi_eve_clave', models.CharField(max_length=45)),
            ],
        ),
    ]
