# Generated by Django 5.2.1 on 2025-05-26 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistentes',
            fields=[
                ('asi_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('asi_nombre', models.CharField(max_length=100)),
                ('asi_correo', models.CharField(max_length=100)),
                ('asi_telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AsistentesEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asi_eve_fecha_hora', models.DateTimeField()),
                ('asi_eve_soporte', models.CharField(blank=True, max_length=255, null=True)),
                ('asi_eve_estado', models.CharField(max_length=45)),
                ('asi_eve_clave', models.CharField(max_length=45)),
                ('asi_eve_asistente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registros.asistentes')),
                ('asi_eve_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento')),
            ],
            options={
                'unique_together': {('asi_eve_asistente_fk', 'asi_eve_evento_fk')},
            },
        ),
    ]
