# Generated by Django 5.2.1 on 2025-06-17 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_eventos', '0001_initial'),
        ('app_registros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistentes',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistenteseventos',
            name='asi_eve_asistente_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registros.asistentes'),
        ),
        migrations.AddField(
            model_name='asistenteseventos',
            name='asi_eve_evento_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento'),
        ),
        migrations.AlterUniqueTogether(
            name='asistenteseventos',
            unique_together={('asi_eve_asistente_fk', 'asi_eve_evento_fk')},
        ),
    ]
