# Generated by Django 5.2.1 on 2025-12-10 19:48

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MemoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='archivo_memoria')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('descripcion_proyecto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('eve_id', models.AutoField(primary_key=True, serialize=False)),
                ('eve_nombre', models.CharField(max_length=100)),
                ('eve_descripcion', models.CharField(blank=True, max_length=400, null=True)),
                ('eve_ciudad', models.CharField(blank=True, max_length=45, null=True)),
                ('eve_lugar', models.CharField(blank=True, max_length=45, null=True)),
                ('eve_fecha_inicio', models.DateField(blank=True, null=True)),
                ('eve_fecha_fin', models.DateField(blank=True, null=True)),
                ('eve_estado', models.CharField(blank=True, max_length=45, null=True)),
                ('cobro', models.CharField(default='No', max_length=2)),
                ('cupos', models.IntegerField(blank=True, null=True)),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen')),
                ('archivo_programacion', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='archivo_programacion')),
                ('inscripciones_participantes_abiertas', models.BooleanField(default=True)),
                ('inscripciones_asistentes_abiertas', models.BooleanField(default=True)),
                ('inscripciones_evaluadores_abiertas', models.BooleanField(default=True)),
                ('adm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app_admin.administradorevento')),
            ],
        ),
    ]
