# Generated by Django 5.2.1 on 2025-05-26 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin', '0001_initial'),
        ('app_super_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('eve_id', models.AutoField(primary_key=True, serialize=False)),
                ('eve_nombre', models.CharField(max_length=100)),
                ('eve_descripcion', models.CharField(blank=True, max_length=400, null=True)),
                ('eve_ciudad', models.CharField(blank=True, max_length=45, null=True)),
                ('eve_lugar', models.CharField(blank=True, max_length=45, null=True)),
                ('eve_fecha_inicio', models.DateField(blank=True, null=True)),
                ('eve_fecha_fin', models.DateField(blank=True, null=True)),
                ('eve_estado', models.CharField(blank=True, max_length=45, null=True)),
                ('cobro', models.CharField(default='No', max_length=2)),
                ('cupos', models.IntegerField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo_programacion', models.CharField(blank=True, max_length=255, null=True)),
                ('inscripciones_participantes_abiertas', models.BooleanField(default=True)),
                ('inscripciones_asistentes_abiertas', models.BooleanField(default=True)),
                ('adm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app_admin.administradorevento')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_super_admin.categoria')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento')),
            ],
            options={
                'unique_together': {('evento', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='categorias',
            field=models.ManyToManyField(related_name='eventos', through='app_eventos.EventoCategoria', to='app_super_admin.categoria'),
        ),
    ]
