# Generated by Django 5.2.1 on 2025-12-11 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_eventos', '0001_initial'),
        ('app_super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_super_admin.categoria'),
        ),
        migrations.AddField(
            model_name='eventocategoria',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='categorias',
            field=models.ManyToManyField(related_name='eventos', through='app_eventos.EventoCategoria', to='app_super_admin.categoria'),
        ),
        migrations.AddField(
            model_name='memoriaevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorias', to='app_eventos.evento'),
        ),
    ]
