# Generated by Django 5.2.1 on 2025-06-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='inscripciones_evaluadores_abiertas',
            field=models.BooleanField(default=True),
        ),
    ]
