# Generated by Django 5.2.1 on 2025-07-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0002_memoriaevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoriaevento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='memorias_evento/'),
        ),
    ]
