# Generated by Django 5.2.1 on 2025-12-10 16:41

import imagekitio_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0002_memoriaevento_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='archivo_programacion',
            field=models.FileField(blank=True, null=True, storage=imagekitio_storage.storage.MediaImagekitStorage(), upload_to='programacion/eventos/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=imagekitio_storage.storage.MediaImagekitStorage(), upload_to='imagenes/eventos/'),
        ),
        migrations.AlterField(
            model_name='memoriaevento',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=imagekitio_storage.storage.MediaImagekitStorage(), upload_to='memorias_evento/'),
        ),
    ]
