# Generated by Django 5.2.1 on 2025-09-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0004_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='app_eventos.evento'),
        ),
    ]
