# Generated by Django 5.2.1 on 2025-09-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0005_proyecto_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='descripcion',
            new_name='descripcion_proyecto',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='nombre',
            new_name='nombre_proyecto',
        ),
    ]
