# Generated by Django 5.2.1 on 2025-09-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0006_rename_descripcion_proyecto_descripcion_proyecto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='descripcion_proyecto',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='nombre_proyecto',
            new_name='nombre',
        ),
    ]
