# Generated by Django 5.2.1 on 2025-05-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorEvento',
            fields=[
                ('adm_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('adm_nombre', models.CharField(max_length=100)),
                ('adm_correo', models.CharField(max_length=100)),
                ('adm_telefono', models.CharField(max_length=45)),
            ],
        ),
    ]
