# Generated by Django 5.2.1 on 2025-12-09 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('titulo', models.CharField(blank=True, default='CERTIFICADO DE PARTICIPACIÓN', max_length=255)),
                ('subtitulo', models.CharField(blank=True, default='Se otorga el presente certificado a', max_length=255)),
                ('texto_firma', models.CharField(blank=True, default='Coordinador del Evento', max_length=255)),
                ('color_fondo', models.CharField(blank=True, default='#FFFFFF', max_length=7)),
                ('color_borde', models.CharField(blank=True, default='#000000', max_length=7)),
                ('color_titulo', models.CharField(blank=True, default='#000000', max_length=7)),
                ('color_nombre', models.CharField(blank=True, default='#000000', max_length=7)),
                ('fuente_titulo', models.CharField(blank=True, choices=[('Helvetica', 'Helvetica'), ('Helvetica-Bold', 'Helvetica Bold'), ('Times-Roman', 'Times'), ('Courier', 'Courier')], default='Helvetica-Bold', max_length=50)),
                ('tamano_titulo', models.IntegerField(blank=True, default=28)),
                ('fuente_nombre', models.CharField(blank=True, choices=[('Helvetica', 'Helvetica'), ('Helvetica-Bold', 'Helvetica Bold'), ('Times-Roman', 'Times'), ('Courier', 'Courier')], default='Helvetica-Bold', max_length=50)),
                ('tamano_nombre', models.IntegerField(blank=True, default=24)),
                ('borde_grosor', models.IntegerField(blank=True, default=3)),
                ('borde_margen', models.IntegerField(blank=True, default=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificados/logos/')),
                ('sello', models.ImageField(blank=True, null=True, upload_to='certificados/sellos/')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='certificados/firmas/')),
            ],
        ),
        migrations.AddField(
            model_name='administradorevento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='administradorevento',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='administradorevento',
            name='limite_eventos',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='administradorevento',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrador_evento', to=settings.AUTH_USER_MODEL),
        ),
    ]
