# Generated by Django 5.2.1 on 2025-07-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradorevento',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
