# Generated by Django 5.2.1 on 2025-07-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_administradorevento_aprobado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Plantilla por defecto', max_length=100)),
                ('titulo', models.CharField(default='🎓 CERTIFICADO', max_length=100)),
                ('subtitulo', models.CharField(default='Se otorga el presente certificado a', max_length=200)),
                ('color_titulo', models.CharField(default='#00008B', max_length=20)),
                ('color_nombre', models.CharField(default='#8B0000', max_length=20)),
                ('mostrar_firma', models.BooleanField(default=True)),
                ('texto_firma', models.CharField(default='Coordinador del Evento', max_length=100)),
                ('pos_titulo_y', models.FloatField(default=4.0)),
                ('pos_nombre_y', models.FloatField(default=8.0)),
            ],
        ),
    ]
