# Generated by Django 5.2.1 on 2025-07-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_plantillacertificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillacertificado',
            name='color_fondo',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
