# Generated by Django 5.2.1 on 2025-07-28 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_plantillacertificado_color_fondo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillacertificado',
            name='color_fondo',
        ),
    ]
