# Generated by Django 5.2.1 on 2025-07-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_remove_plantillacertificado_color_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillacertificado',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/logos/'),
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='sello',
            field=models.ImageField(blank=True, null=True, upload_to='static/sellos/'),
        ),
    ]
