# Generated by Django 5.2.1 on 2025-07-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0007_plantillacertificado_logo_plantillacertificado_sello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillacertificado',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/logos/'),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='sello',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/sellos/'),
        ),
    ]
