# Generated by Django 5.2.1 on 2025-09-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0008_alter_plantillacertificado_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradorevento',
            name='limite_eventos',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
