# Generated by Django 5.2.1 on 2025-09-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0009_administradorevento_limite_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradorevento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
