# Generated by Django 5.2.1 on 2025-09-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0010_administradorevento_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillacertificado',
            name='borde_grosor',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='borde_margen',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='color_borde',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='color_fondo',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='fuente_nombre',
            field=models.CharField(choices=[('Helvetica', 'Helvetica'), ('Helvetica-Bold', 'Helvetica Bold'), ('Times-Roman', 'Times'), ('Courier', 'Courier')], default='Helvetica-Bold', max_length=50),
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='fuente_titulo',
            field=models.CharField(choices=[('Helvetica', 'Helvetica'), ('Helvetica-Bold', 'Helvetica Bold'), ('Times-Roman', 'Times'), ('Courier', 'Courier')], default='Helvetica-Bold', max_length=50),
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='pos_subtitulo_y',
            field=models.FloatField(default=700),
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='tamano_nombre',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='tamano_titulo',
            field=models.IntegerField(default=28),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='color_nombre',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='color_titulo',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='pos_nombre_y',
            field=models.FloatField(default=650),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='pos_titulo_y',
            field=models.FloatField(default=750),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='subtitulo',
            field=models.CharField(default='Se otorga el presente certificado a', max_length=255),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='texto_firma',
            field=models.CharField(default='Coordinador del Evento', max_length=255),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='titulo',
            field=models.CharField(default='CERTIFICADO DE PARTICIPACIÓN', max_length=255),
        ),
    ]
