# Generated by Django 5.2.1 on 2025-09-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0011_plantillacertificado_borde_grosor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillacertificado',
            name='borde_grosor',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='borde_margen',
            field=models.IntegerField(blank=True, default=50),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='color_borde',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='color_fondo',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='color_nombre',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='color_titulo',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='fuente_nombre',
            field=models.CharField(blank=True, choices=[('Helvetica', 'Helvetica'), ('Helvetica-Bold', 'Helvetica Bold'), ('Times-Roman', 'Times'), ('Courier', 'Courier')], default='Helvetica-Bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='fuente_titulo',
            field=models.CharField(blank=True, choices=[('Helvetica', 'Helvetica'), ('Helvetica-Bold', 'Helvetica Bold'), ('Times-Roman', 'Times'), ('Courier', 'Courier')], default='Helvetica-Bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='pos_nombre_y',
            field=models.FloatField(blank=True, default=650),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='pos_subtitulo_y',
            field=models.FloatField(blank=True, default=700),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='pos_titulo_y',
            field=models.FloatField(blank=True, default=750),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='subtitulo',
            field=models.CharField(blank=True, default='Se otorga el presente certificado a', max_length=255),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='tamano_nombre',
            field=models.IntegerField(blank=True, default=24),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='tamano_titulo',
            field=models.IntegerField(blank=True, default=28),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='texto_firma',
            field=models.CharField(blank=True, default='Coordinador del Evento', max_length=255),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='titulo',
            field=models.CharField(blank=True, default='CERTIFICADO DE PARTICIPACIÓN', max_length=255),
        ),
    ]
