# Generated by Django 5.2.1 on 2025-09-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0012_alter_plantillacertificado_borde_grosor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillacertificado',
            name='mostrar_firma',
        ),
        migrations.RemoveField(
            model_name='plantillacertificado',
            name='pos_nombre_y',
        ),
        migrations.RemoveField(
            model_name='plantillacertificado',
            name='pos_subtitulo_y',
        ),
        migrations.RemoveField(
            model_name='plantillacertificado',
            name='pos_titulo_y',
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/firmas/'),
        ),
    ]
