# Generated by Django 5.2.1 on 2025-09-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0013_remove_plantillacertificado_mostrar_firma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillacertificado',
            name='logo',
        ),
    ]
