# Generated by Django 5.2.1 on 2025-09-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0014_remove_plantillacertificado_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillacertificado',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/logos/'),
        ),
    ]
