# Generated by Django 5.2.1 on 2025-06-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('EVALUADOR', 'Evaluador'), ('PARTICIPANTE', 'Participante'), ('ASISTENTE', 'Asistente')], default='PARTICIPANTE', max_length=50),
        ),
    ]
