# Generated by Django 5.2.1 on 2025-06-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0004_remove_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('EVALUADOR', 'Evaluador'), ('PARTICIPANTE', 'Participante'), ('ASISTENTE', 'Asistente')], default='PARTICIPANTE', max_length=30),
        ),
    ]
