# Generated by Django 5.2.1 on 2025-06-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0005_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('SUPER_ADMINISTRADOR', 'Super Administrador'), ('ADMINISTRADOR', 'Administrador'), ('EVALUADOR', 'Evaluador'), ('PARTICIPANTE', 'Participante'), ('ASISTENTE', 'Asistente')], default='PARTICIPANTE', max_length=30),
        ),
    ]
