# Generated by Django 5.2.1 on 2025-06-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantesEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_eve_fecha_hora', models.DateTimeField()),
                ('par_eve_documentos', models.CharField(blank=True, max_length=255, null=True)),
                ('par_eve_or', models.CharField(blank=True, max_length=255, null=True)),
                ('par_eve_clave', models.CharField(max_length=45)),
                ('par_estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
            ],
        ),
    ]
