# Generated by Django 5.2.1 on 2025-05-26 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('par_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('par_nombre', models.CharField(max_length=100)),
                ('par_correo', models.CharField(max_length=100)),
                ('par_telefono', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantesEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_eve_fecha_hora', models.DateTimeField()),
                ('par_eve_documentos', models.CharField(blank=True, max_length=255, null=True)),
                ('par_eve_or', models.CharField(blank=True, max_length=255, null=True)),
                ('par_eve_clave', models.CharField(max_length=45)),
                ('par_estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('par_eve_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento')),
                ('par_eve_participante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_participantes.participantes')),
            ],
            options={
                'unique_together': {('par_eve_participante_fk', 'par_eve_evento_fk')},
            },
        ),
    ]
