# Generated by Django 5.2.1 on 2025-12-10 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_eventos', '0003_initial'),
        ('app_participantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participantes',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participanteseventos',
            name='par_eve_evento_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento'),
        ),
        migrations.AddField(
            model_name='participanteseventos',
            name='par_eve_participante_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_participantes.participantes'),
        ),
        migrations.AddField(
            model_name='participanteseventos',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes_evento', to='app_eventos.proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='participanteseventos',
            unique_together={('par_eve_participante_fk', 'par_eve_evento_fk')},
        ),
    ]
