# Generated by Django 5.2.1 on 2025-09-13 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0004_proyecto'),
        ('app_participantes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteseventos',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes_evento', to='app_eventos.proyecto'),
        ),
    ]
