"""
Django settings for pr_gestion_eventos project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0zorp&j_3@*p(+@t=ubqn-=sc_68x3kb0lh+en9p8)&fmxzyqh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'app_admin',
    'app_evaluadores',
    'app_eventos',
    'app_main',
    'app_participantes',
    'app_qr',
    'app_registros',
    'app_super_admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pr_gestion_eventos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'app_admin/templates', 
            'app_evaluadores/templates', 
            'app_eventos/templates', 
            'app_main/templates',  # Agregué /templates
            'app_participantes/templates',  # Agregué /templates
            'app_qr/templates', 
            'app_registros/templates', 
            'app_super_admin/templates',
            os.path.join(BASE_DIR, 'templates'),  # Carpeta global de templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pr_gestion_eventos.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'eventos',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'es-es'  # Cambiado a español
TIME_ZONE = 'America/Bogota'  # Ajusta según tu zona horaria
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR / 'static'),
]

# Media files (archivos subidos por usuarios)


# ========================================
# CONFIGURACIÓN PERSONALIZADA PARA ARCHIVOS
# ========================================

# Carpetas de uploads específicas (compatibles con Flask)
UPLOAD_FOLDER_IMAGENES = os.path.join(BASE_DIR, 'static', 'imagenes')
UPLOAD_FOLDER_PAGOS = os.path.join(BASE_DIR, 'static', 'uploads')
UPLOAD_FOLDER_PROGRAMACION = os.path.join(BASE_DIR, 'static', 'programacion')

# Extensiones permitidas
ALLOWED_EXTENSIONS_IMAGENES = {'png', 'jpg', 'jpeg', 'gif'}
ALLOWED_EXTENSIONS_PAGOS = {'png', 'jpg', 'jpeg', 'pdf'}
ALLOWED_EXTENSIONS_PROGRAMACION = {'pdf'}

# Tamaños máximos de archivo (en bytes)
MAX_FILE_SIZE_IMAGENES = 5 * 1024 * 1024      # 5MB
MAX_FILE_SIZE_PAGOS = 10 * 1024 * 1024        # 10MB
MAX_FILE_SIZE_PROGRAMACION = 50 * 1024 * 1024  # 50MB

# Configuración agrupada para fácil acceso
UPLOAD_SETTINGS = {
    'FOLDERS': {
        'imagenes': UPLOAD_FOLDER_IMAGENES,
        'pagos': UPLOAD_FOLDER_PAGOS,
        'programacion': UPLOAD_FOLDER_PROGRAMACION,
    },
    'ALLOWED_EXTENSIONS': {
        'imagenes': ALLOWED_EXTENSIONS_IMAGENES,
        'pagos': ALLOWED_EXTENSIONS_PAGOS,
        'programacion': ALLOWED_EXTENSIONS_PROGRAMACION,
    },
    'MAX_SIZES': {
        'imagenes': MAX_FILE_SIZE_IMAGENES,
        'pagos': MAX_FILE_SIZE_PAGOS,
        'programacion': MAX_FILE_SIZE_PROGRAMACION,
    }
}

# ========================================
# CONFIGURACIÓN DE EMAIL (OPCIONAL)
# ========================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tu_email@gmail.com'  # Cambiar por tu email
EMAIL_HOST_PASSWORD = 'tu_password_app'   # Cambiar por tu contraseña de app

# ========================================
# CONFIGURACIÓN DE SEGURIDAD
# ========================================
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Para producción (descomenta cuando vayas a producción)
# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========================================
# FUNCIONES AUXILIARES
# ========================================
def create_upload_folders():
    """Crear carpetas de upload si no existen"""
    folders = [
        UPLOAD_FOLDER_IMAGENES,
        UPLOAD_FOLDER_PAGOS,
        UPLOAD_FOLDER_PROGRAMACION,
        
        os.path.join(BASE_DIR, 'static'),
    ]
    
    for folder in folders:
        os.makedirs(folder, exist_ok=True)

def is_allowed_file(filename, file_type='imagenes'):
    """Verificar si el archivo tiene una extensión permitida"""
    if '.' not in filename:
        return False
    
    extension = filename.rsplit('.', 1)[1].lower()
    return extension in UPLOAD_SETTINGS['ALLOWED_EXTENSIONS'].get(file_type, set())

# Crear carpetas al cargar configuración
create_upload_folders()

# ========================================
# CONFIGURACIÓN ESPECÍFICA PARA QR
# ========================================
QR_SETTINGS = {
    'DEFAULT_SIZE': 10,
    'DEFAULT_BORDER': 4,
    'FORMAT': 'PNG',
    'FILL_COLOR': 'black',
    'BACK_COLOR': 'white',
}

# ========================================
# CONFIGURACIONES ADICIONALES PARA TUS APPS
# ========================================

# Configuración para app_eventos
EVENTOS_SETTINGS = {
    'MAX_PARTICIPANTES_DEFAULT': 100,
    'DIAS_LIMITE_INSCRIPCION': 7,
    'FORMATO_FECHA': '%d/%m/%Y',
}

# Configuración para app_registros
REGISTROS_SETTINGS = {
    'GENERAR_OR_AUTOMATICO': True,
    'PREFIJO_OR': 'OR-',
    'LONGITUD_OR': 8,
}

# Configuración para notificaciones
NOTIFICATIONS_SETTINGS = {
    'SEND_EMAIL_CONFIRMATION': True,
    'ADMIN_EMAIL': 'admin@tueventos.com',
    'FROM_EMAIL': 'noreply@tueventos.com',
}



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'juanestebanmarulandalopez407@gmail.com'         # Reemplaza por tu correo real
EMAIL_HOST_PASSWORD = 'tnxy tzxx zgxf etqc'    # Pon aquí la contraseña de aplicación que creaste
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Usar el mismo correo como remitente por defecto


DEBUG = False
ALLOWED_HOSTS = ['Juanes17066.pythonanywhere.com']
