# Generated by Django 5.2.1 on 2025-06-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cal_valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('cri_id', models.AutoField(primary_key=True, serialize=False)),
                ('cri_descripcion', models.CharField(max_length=100)),
                ('cri_peso', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluadorEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva_eve_fecha_hora', models.DateTimeField()),
                ('eva_eve_documentos', models.CharField(blank=True, max_length=255, null=True)),
                ('eva_eve_or', models.CharField(blank=True, max_length=255, null=True)),
                ('eva_eve_clave', models.CharField(max_length=45)),
                ('eva_estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InformacionTecnica',
            fields=[
                ('inf_id', models.AutoField(primary_key=True, serialize=False)),
                ('inf_nombre', models.CharField(max_length=100)),
                ('inf_descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('inst_id', models.AutoField(primary_key=True, serialize=False)),
                ('inst_tipo', models.CharField(max_length=50)),
                ('inst_descripcion', models.TextField()),
            ],
        ),
    ]
