# Generated by Django 5.2.1 on 2025-05-26 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_eventos', '0001_initial'),
        ('app_participantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('cri_id', models.AutoField(primary_key=True, serialize=False)),
                ('cri_descripcion', models.CharField(max_length=100)),
                ('cri_peso', models.FloatField()),
                ('cri_evento_fk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('inst_id', models.AutoField(primary_key=True, serialize=False)),
                ('inst_tipo', models.CharField(max_length=50)),
                ('inst_descripcion', models.TextField()),
                ('inst_evento_fk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('eva_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('eva_nombre', models.CharField(max_length=100)),
                ('eva_correo', models.CharField(max_length=100)),
                ('eva_telefono', models.CharField(max_length=45)),
                ('eventos', models.ManyToManyField(related_name='evaluadores', to='app_eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cal_valor', models.IntegerField()),
                ('cal_participante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_participantes.participantes')),
                ('cal_criterio_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evaluadores.criterio')),
                ('cal_evaluador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evaluadores.evaluador')),
            ],
        ),
    ]
