# Generated by Django 5.2.1 on 2025-06-17 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_evaluadores', '0001_initial'),
        ('app_eventos', '0001_initial'),
        ('app_participantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='cal_participante_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_participantes.participantes'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='cri_evento_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='cal_criterio_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evaluadores.criterio'),
        ),
    ]
