# Generated by Django 5.2.1 on 2025-06-17 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_evaluadores', '0002_initial'),
        ('app_eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='cal_evaluador_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evaluadores.evaluador'),
        ),
        migrations.AddField(
            model_name='evaluadoreventos',
            name='eva_eve_evaluador_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evaluadores.evaluador'),
        ),
        migrations.AddField(
            model_name='evaluadoreventos',
            name='eva_eve_evento_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento'),
        ),
        migrations.AddField(
            model_name='evaluador',
            name='eventos',
            field=models.ManyToManyField(related_name='evaluadores', through='app_evaluadores.EvaluadorEventos', to='app_eventos.evento'),
        ),
        migrations.AddField(
            model_name='informaciontecnica',
            name='inf_evento_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='inst_evento_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluadoreventos',
            unique_together={('eva_eve_evaluador_fk', 'eva_eve_evento_fk')},
        ),
    ]
