# Generated by Django 5.2.1 on 2025-06-16 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluadores', '0004_evaluadoreseventos'),
        ('app_eventos', '0002_evento_inscripciones_evaluadores_abiertas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluadorEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva_eve_fecha_hora', models.DateTimeField()),
                ('eva_eve_documentos', models.CharField(blank=True, max_length=255, null=True)),
                ('eva_eve_or', models.CharField(blank=True, max_length=255, null=True)),
                ('eva_eve_clave', models.CharField(max_length=45)),
                ('eva_estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('eva_eve_evaluador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evaluadores.evaluador')),
                ('eva_eve_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento')),
            ],
            options={
                'unique_together': {('eva_eve_evaluador_fk', 'eva_eve_evento_fk')},
            },
        ),
        migrations.DeleteModel(
            name='EvaluadoresEventos',
        ),
    ]
