# Generated by Django 5.2.1 on 2025-06-16 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluadores', '0005_evaluadoreventos_delete_evaluadoreseventos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluador',
            name='eventos',
        ),
    ]
