# Generated by Django 5.2.1 on 2025-06-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluadores', '0006_remove_evaluador_eventos'),
        ('app_eventos', '0002_evento_inscripciones_evaluadores_abiertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluador',
            name='eventos',
            field=models.ManyToManyField(related_name='evaluadores', through='app_evaluadores.EvaluadorEventos', to='app_eventos.evento'),
        ),
    ]
