# Generated by Django 5.2.1 on 2025-06-16 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluadores', '0007_evaluador_eventos'),
        ('app_eventos', '0002_evento_inscripciones_evaluadores_abiertas'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionTecnica',
            fields=[
                ('inf_id', models.AutoField(primary_key=True, serialize=False)),
                ('inf_nombre', models.CharField(max_length=100)),
                ('inf_descripcion', models.TextField()),
                ('inf_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento')),
            ],
        ),
    ]
